name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your contribution! If this is your first time here please reade the README.md file.'
        pr-message: 'Thanks for your contribution! If this is your first time here please reade the README.md file, in particular the Pull Request section.'
